speaking_kd1= {
      "1": "hello",
      "2": "let me introduce myself",
      "3": "my name is Budi",
      "4": "I live in Pati",
      "5": "I go to SMKN 2 Pati",
      "6": "I major in electrical engineering",
      "7": "my name is Wati",
      "8": "I like playing football",
      "9": "I like reading",
      "10": "may I know your name?",
      "11": "nice to know you",
      "12": "how are you?",
      "13": "how do you do?",
      "14": "good morning",
      "15": "good afternoon",
      "16": "good evening",
      "17": "good night",
      "18": "good bye",
      "19": "glad to know you",
      "20": "fancy meeting you"
   };
speaking_kd2= {
      "1": "I heard you just won a competition",
      "2": "congratulations on your success!",
      "3": "congratulations!",
      "4": "I am glad for your success",
      "5": "you are really great!",
      "6": "you are really terrific!",
      "7": "well done!",
      "8": "good job!",
      "9": "you are the best!",
      "10": "you are the man!",
      "11": "I would like to congratulate you !",
      "12": "I would like to congratulate you for your success!",
      "13": "that's great!",
      "14": "you deserve it!",
      "15": "I am really glad for your success!",
      "16": "I heard that you have been promoted",
      "17": "I heard that you received a scholarship",
      "18": "you are great!",
      "19": "you are the one!",
      "20": "congrats!"
   };
